"""Shared-language region and fixed AUTO checks; no remote services required."""
import json

def verify_region_menu(page, root, tag, size, check):
    rows=json.loads((root/'tests/fixtures/regions-v061.json').read_text(encoding='utf8'))
    page.locator('#language-toggle').click()
    auto=page.locator('[data-language-auto]');scroller=page.locator('#language-scroll')
    check(auto.evaluate("e=>!document.getElementById('language-scroll').contains(e)"),tag+' AUTO is outside the scroller')
    before=auto.bounding_box()
    scroller.evaluate('e=>e.scrollTop=e.scrollHeight');page.wait_for_timeout(50)
    after=auto.bounding_box()
    check(abs(before['y']-after['y'])<.1 and abs(before['height']-after['height'])<.1,tag+' AUTO does not move at the bottom')
    check(auto.evaluate('e=>{const b=e.getBoundingClientRect();return e.contains(document.elementFromPoint(b.x+b.width/2,b.y+b.height/2))}'),tag+' fixed AUTO remains clickable')
    bounds=page.locator('#language-menu').bounding_box()
    check(bounds['y']>=0 and bounds['y']+bounds['height']<=size[1]+1,tag+' language menu fits viewport')
    scroller.evaluate('e=>e.scrollTop=0');box=scroller.bounding_box();page.mouse.move(box['x']+box['width']/2,box['y']+box['height']/2);page.mouse.wheel(0,300);page.wait_for_timeout(120)
    check(scroller.evaluate('e=>e.scrollTop')>0 and abs(auto.bounding_box()['y']-before['y'])<.1,tag+' wheel scrolls countries only')
    auto.focus();page.keyboard.press('End')
    check(page.evaluate("document.activeElement.dataset.language==='ve'"),tag+' End reaches last country')
    page.keyboard.press('Home')
    check(auto.evaluate('e=>document.activeElement===e'),tag+' Home reaches fixed AUTO')
    page.keyboard.press('ArrowDown')
    check(page.evaluate("document.activeElement.dataset.language==='ao'"),tag+' ArrowDown reaches first country')
    page.keyboard.press('Escape');page.wait_for_timeout(180)
    page.evaluate("()=>{window.__regionFeatures=[];const r=SolarTime.renderer,original=r.animateFeature.bind(r);r.animateFeature=(...args)=>{__regionFeatures.push(args);return original(...args)}}")
    for row in rows:
        code=row['code'];page.locator('#language-toggle').click();choice=page.locator('[data-language="'+code+'"]');choice.scroll_into_view_if_needed()
        fits=choice.locator('span').evaluate('e=>{const t=document.createRange();t.selectNodeContents(e);const b=t.getBoundingClientRect(),p=e.closest("button").getBoundingClientRect();return b.left>=p.left&&b.right<=p.right+.5}')
        check(fits,tag+' '+code+' full country label fits')
        choice.click();page.wait_for_function('c=>SolarTime.getState().language===c',arg=code)
        state=page.evaluate('SolarTime.getState()')
        check(state['languageMode']=='manual' and state['copyLanguage']==row['copy'] and state['timeZone']==row['timeZone'] and state['region']==row['label'],tag+' '+code+' language/region/zone linked')
        check(page.locator('html').get_attribute('lang')==row['locale'],tag+' '+code+' document locale')
        check(page.evaluate("JSON.parse(localStorage.getItem('eg.solar-time.v0.01')).language")==code,tag+' '+code+' selection saved')
        check(page.evaluate("SolarTime.translate('timer')")==('Timer' if row['copy']=='en' else 'Temporizador'),tag+' '+code+' shared timer translation')
        # Inspect the existing Earth location action without changing camera behavior.
        page.locator('#timezone-button').click();args=page.evaluate('__regionFeatures.at(-1)')
        check(args[0]=='earth' and abs(args[1]-row['latitude'])<1e-8 and abs(args[2]-row['longitude'])<1e-8,tag+' '+code+' Earth-view coordinates')
        if page.locator('#body-close').is_visible():page.locator('#body-close').click()
    requests=page.evaluate('__fixtureRequests')
    check(all(not any('/locales/'+r['code']+'.json' in u for u in requests) for r in rows),tag+' no per-country translation download')
    check(sum('/locales/en.json' in u for u in requests)==1 and sum('/locales/es.json' in u for u in requests)==1,tag+' shared English/Spanish each loaded once')
    page.locator('#language-toggle').click();page.locator('[data-language-auto]').click()
    page.wait_for_function("SolarTime.getState().languageMode==='auto'")
    check(page.evaluate("SolarTime.getState().language==='kor'&&SolarTime.getState().timeZone==='Asia/Seoul'"),tag+' fixed AUTO restores device region/time')
