"""Offline UI regression checks. Requires Python Playwright and a Chromium executable.
The test injects the standalone HTML directly, so it needs neither a server nor network access.
Usage: CHROMIUM_PATH=/usr/bin/chromium python tests/browser_test.py
"""
from __future__ import annotations
import json
import os
from pathlib import Path
from time import perf_counter
from playwright.sync_api import sync_playwright

ROOT=Path(__file__).resolve().parents[1]
HTML=(ROOT/'dist'/'Solar-Time_v0.01.html').read_text(encoding='utf-8')
OUT=ROOT/'test-results'
OUT.mkdir(exist_ok=True)
results=[]

def check(name,condition):
    if not condition:
        raise AssertionError(name)
    results.append({'test':name,'passed':True})
    print('PASS',name)

with sync_playwright() as pw:
    executable=os.environ.get('CHROMIUM_PATH','/usr/bin/chromium')
    browser=pw.chromium.launch(executable_path=executable,headless=True,args=['--no-sandbox','--disable-dev-shm-usage'])
    page=browser.new_page(viewport={'width':1648,'height':928},device_scale_factor=1,timezone_id='Asia/Seoul')
    errors=[];requests=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.on('request',lambda r:requests.append(r.url))
    page.set_content(HTML,wait_until='load')
    page.wait_for_function('!!window.SolarTime',timeout=30000)
    page.wait_for_timeout(650)
    state=page.evaluate('SolarTime.getState()')
    check('Starts in actual, playing local time',state['live'] and not state['paused'] and state['rate']==1)
    check('Actual clock synchronized with wall time',abs(state['simulationMs']-state['wallMs'])<5)
    check('Sun, 8 planets, Pluto and Moon render',page.evaluate('SolarTime.renderer.projected.length')==11)
    check('No external network requests',not requests)
    check('Loading overlay dismissed',page.locator('#loading').is_hidden())
    check('All default orbit paths fit inside the viewport',page.evaluate('SolarTime.renderer.paths.every(path=>path.points.every(p=>{const q=SolarTime.renderer.project(p);return q.x>=0&&q.x<=innerWidth&&q.y>=180&&q.y<=innerHeight-175;}))'))
    page.screenshot(path=str(OUT/'desktop.png'))
    page.locator('[data-rate="86400"]').click()
    sample1=page.evaluate('({s:SolarTime.getState(),p:performance.now()})')
    page.wait_for_timeout(800)
    sample2=page.evaluate('({s:SolarTime.getState(),p:performance.now()})')
    ratio=(sample2['s']['simulationMs']-sample1['s']['simulationMs'])/(sample2['p']-sample1['p'])
    check('One day per second advances simulation at ×86400',abs(ratio-86400)<100)
    check('Time travel leaves the actual wall clock unaccelerated',sample2['s']['wallMs']-sample1['s']['wallMs']<1500)
    page.locator('#pause-button').click()
    page.wait_for_timeout(120)
    frozen=page.evaluate('SolarTime.getState()')
    before_image=page.evaluate('document.getElementById("universe").toDataURL()')
    page.wait_for_timeout(450)
    after=page.evaluate('SolarTime.getState()')
    after_image=page.evaluate('document.getElementById("universe").toDataURL()')
    check('Pause freezes simulation time',frozen['simulationMs']==after['simulationMs'])
    check('Pause freezes Sun and stars as well',frozen['effectTime']==after['effectTime'] and before_image==after_image)
    check('Pause shows the play SVG icon',page.locator('#play-icon').is_visible() and page.locator('#pause-icon').is_hidden())
    page.locator('#pause-button').click();page.wait_for_timeout(100)
    check('Resuming continues accelerated playback',not page.evaluate('SolarTime.getState().paused'))
    page.locator('#live-button').click();page.wait_for_timeout(80)
    state=page.evaluate('SolarTime.getState()')
    check('Actual-time button resets rate and date',state['live'] and state['rate']==1 and abs(state['simulationMs']-state['wallMs'])<5)
    page.locator('[data-body="earth"]').click()
    check('Keyboard-accessible Earth selector opens details',page.locator('#body-panel').is_visible() and page.locator('#body-name').inner_text()=='지구')
    page.screenshot(path=str(OUT/'earth-details.png'))
    page.locator('#body-close').click()
    page.locator('#settings-button').click()
    check('Settings panel opens',page.locator('#settings-panel').is_visible())
    page.locator('#show-pluto').uncheck();page.wait_for_timeout(60)
    check('Pluto visibility toggles both orbit and navigation',not page.evaluate('SolarTime.renderer.projected.some(p=>p.body.id==="pluto")') and page.locator('[data-body="pluto"]').is_hidden())
    page.locator('#show-pluto').check()
    page.locator('#show-moon').uncheck();page.wait_for_timeout(60)
    check('Moon visibility toggle works',not page.evaluate('SolarTime.renderer.projected.some(p=>p.body.id==="moon")'))
    page.locator('#show-moon').check()
    page.locator('#show-activity').uncheck();page.wait_for_timeout(100)
    s1=page.evaluate('SolarTime.renderer.sprites.get("sun").canvas.toDataURL()')
    page.wait_for_timeout(700)
    s2=page.evaluate('SolarTime.renderer.sprites.get("sun").canvas.toDataURL()')
    check('Disabling Sun activity freezes its texture',s1==s2)
    page.locator('#show-activity').check()
    page.locator('#show-labels').uncheck()
    check('Label setting reaches renderer',not page.evaluate('SolarTime.renderer.options.labels'))
    page.locator('#show-labels').check()
    page.locator('#quality').select_option('low')
    check('Low-power rendering limits pixel ratio',page.evaluate('SolarTime.renderer.dpr')<=1)
    page.locator('#quality').select_option('auto')
    page.locator('#settings-close').click()
    page.locator('#timezone-button').click()
    check('Time zone can switch to UTC',page.evaluate('SolarTime.getState().timezone')=='utc')
    page.locator('#date-button').click();page.locator('#date-input').fill('2040-01-01T12:30');page.locator('#date-form button[type="submit"]').click()
    state=page.evaluate('SolarTime.getState()')
    check('Selected date is exact in UTC and starts paused',state['simulationMs']==2209033800000 and state['paused'] and not state['live'])
    page.locator('[data-rate="604800"]').click();page.wait_for_timeout(100)
    check('Speed button resumes a selected date',page.evaluate('SolarTime.getState().rate')==604800 and not page.evaluate('SolarTime.getState().paused'))
    page.locator('#live-button').click();page.locator('#timezone-button').click()
    page.locator('#help-button').click()
    check('Help is a modal dialog with accuracy disclosure',page.locator('#help-dialog').is_visible() and '정확도' in page.locator('#help-dialog').inner_text())
    page.keyboard.press('Escape')
    check('Escape closes native modal',page.locator('#help-dialog').is_hidden())
    a=page.evaluate('SolarTime.renderer.camera.azimuth')
    page.mouse.move(630,570);page.mouse.down();page.mouse.move(745,590,steps=6);page.mouse.up()
    check('Dragging rotates camera',abs(page.evaluate('SolarTime.renderer.camera.azimuth')-a)>.2)
    z=page.evaluate('SolarTime.renderer.camera.zoom');page.mouse.wheel(0,-100);page.wait_for_timeout(80)
    check('Mouse wheel zooms the view',page.evaluate('SolarTime.renderer.camera.zoom')>z)
    page.locator('#fit-view').click()
    check('Reset restores 45-degree view and unit zoom',page.evaluate('Math.abs(SolarTime.renderer.camera.elevation-Math.PI/4)<1e-8 && SolarTime.renderer.camera.zoom===1'))
    page.locator('#hide-ui').click()
    check('Viewing mode hides controls but keeps real clock',page.locator('.playback').is_hidden() and page.locator('#wall-clock').is_visible())
    page.locator('#show-ui').click()
    check('Viewing mode has a working exit',page.locator('.playback').is_visible())
    page.locator('#universe').focus();page.keyboard.press('Space')
    check('Space keyboard shortcut pauses',page.evaluate('SolarTime.getState().paused'))
    page.keyboard.press('r')
    check('R keyboard shortcut returns to NOW',page.evaluate('SolarTime.getState().live') and not page.evaluate('SolarTime.getState().paused'))
    check('No runtime errors during desktop interactions',not errors)
    f0=page.evaluate('SolarTime.renderer.frameCount');t0=perf_counter();page.wait_for_timeout(1200);f1=page.evaluate('SolarTime.renderer.frameCount');fps=(f1-f0)/(perf_counter()-t0)
    print('Measured desktop FPS:',round(fps,1))
    # Mobile geometry, accessible controls, and two-finger interaction handlers.
    mobile=browser.new_page(viewport={'width':390,'height':844},device_scale_factor=2,is_mobile=True,has_touch=True,timezone_id='Asia/Seoul')
    mobile_errors=[];mobile.on('pageerror',lambda e:mobile_errors.append(str(e)))
    mobile.set_content(HTML);mobile.wait_for_function('!!window.SolarTime',timeout=30000);mobile.wait_for_timeout(650)
    check('Mobile starts with all bodies',mobile.evaluate('SolarTime.renderer.projected.length')==11)
    check('Mobile playback bar stays within viewport',mobile.evaluate('(()=>{const r=document.querySelector(".playback-bar").getBoundingClientRect();return r.left>=0&&r.right<=innerWidth;})()'))
    check('Mobile page has no horizontal body overflow',mobile.evaluate('document.documentElement.scrollWidth<=innerWidth'))
    mobile.screenshot(path=str(OUT/'mobile.png'))
    mobile.locator('[data-rate="31557600"]').tap();mobile.wait_for_timeout(350)
    check('Mobile speed selection works',mobile.evaluate('SolarTime.getState().rate')==31557600)
    mobile.locator('#settings-button').tap()
    check('Mobile settings fit and scroll within viewport',mobile.evaluate('(()=>{const r=document.querySelector("#settings-panel").getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.bottom<=innerHeight;})()'))
    mobile.locator('#settings-close').tap()
    check('Mobile has no runtime errors',not mobile_errors)
    # Reduced-motion preference has a quieter initial appearance.
    quiet=browser.new_page(viewport={'width':1280,'height':720},reduced_motion='reduce')
    quiet.set_content(HTML);quiet.wait_for_function('!!window.SolarTime',timeout=30000)
    check('Reduced-motion preference disables decorative animation by default',quiet.evaluate('!SolarTime.renderer.options.twinkle&&!SolarTime.renderer.options.activity'))
    check('Storage restrictions do not stop initialization',quiet.evaluate('!!window.SolarTime'))
    browser.close()
    (OUT/'browser-results.json').write_text(json.dumps({'passed':len(results),'tests':results,'desktop_fps':round(fps,1),'errors':errors+mobile_errors,'network_requests':requests,'execution':'Chromium, standalone HTML injected offline; file:// and HTTP navigation are blocked by the test environment.'},ensure_ascii=False,indent=2),encoding='utf-8')
    print(f'{len(results)} browser checks passed.')
