'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const read=f=>fs.readFileSync(path.join(__dirname,'..',f),'utf8'),gold=require('./fixtures/r6-contracts.json'),style=require('../src/surface-style.js');
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
const canonical=s=>s.replace(/\/\/[^\n]*/g,'').replace(/\s+/g,'').replace(/(?<![\w])(?:\d+\.\d*|\.\d+)/g,x=>String(Number(Number(x).toPrecision(15))));
function surfaceContext(extra={}){const window={SolarSurfaceStyle:style},context={window,URL,Blob,atob,performance,setTimeout,clearTimeout,...extra};vm.createContext(context);vm.runInContext(read('src/surface.js'),context);return {window,context};}
test('v0.47 keeps every previously visible historical release and translation',()=>{const api=require('../src/release-notes.js');assert.equal(api.RELEASES[0].version,'0.48');const old=api.RELEASES.filter(r=>Number(r.version)<0.47).map(r=>({version:r.version,date:r.date,localized:Object.fromEntries(gold.languages.map(c=>[c,api.itemsFor(r,c)]))}));assert.equal(old.length,gold.releaseCount);assert.equal(hash(JSON.stringify(old)),gold.notes);const nav=api.createReleaseNotesNavigator();for(let i=0;i<100;i++)nav.older();assert.equal(nav.current().index,api.RELEASES.length-1);for(let i=0;i<100;i++)nav.newer();assert.equal(nav.current().release.version,'0.48');for(const code of gold.languages)assert.equal(api.itemsFor(api.RELEASES[0],code).length,6);assert.doesNotMatch(read('src/app.js'),/CURRENT_RELEASE_ITEMS|withCurrentRelease/);});
test('the public version is consistent without changing icon revisions',()=>{const html=read('index.html'),version=JSON.parse(read('version.json'));assert.deepEqual(version,{version:'0.48',revision:'r2'});assert.equal(JSON.parse(read('package.json')).version,'0.0.48');assert.equal(JSON.parse(read('package-lock.json')).version,'0.0.48');assert.ok(html.includes('name="solar-time-version" content="0.48"'));assert.ok(html.includes('name="apple-mobile-web-app-status-bar-style" content="default"'));assert.ok(html.includes('apple-touch-icon.png?v=0.46-r3'));});
test('direct planet shader retains the approved r6 numerical source',()=>{const {window}=surfaceContext();assert.equal(hash(canonical(window.SolarSurface.shaderSources.planet)),gold.planetShader);});
test('explicit star shaders keep one owner and the approved density contract',()=>{const fn=()=>{},Ctor=function(){};Ctor.prototype.shaderSource=fn;const Sky=function(){};Sky.prototype.draw=fn;Sky.prototype.decorate=fn;const window={WebGLRenderingContext:Ctor,WebGL2RenderingContext:Ctor,SolarSky:Sky,SolarAssets:{stars:[]}};vm.runInNewContext(read('src/visual-effects.js'),{window});const api=window.SolarVisualEffects,sources=api.starShaderSources('highp');assert.ok(sources.vertex.includes("tinyEnergy"));assert.ok(sources.fragment.includes("covered.x*covered.y"));assert.equal(Ctor.prototype.shaderSource,fn);assert.equal(Sky.prototype.draw,fn);assert.equal(Sky.prototype.decorate,fn);const sky={starCount:30000,stats:{},invalidate(){}};for(const density of [0,1,2,3]){assert.equal(api.drawCount(sky,{starDensity:density}),density*10000);assert.equal(sky.starCount,30000);assert.equal(api.starsFor(sky,{starDensity:density}).length,density*10000);}assert.equal(window.SolarAssets.stars.length,30000);});
test('Renderer alone owns resize while DPR policy remains active',()=>{const window={SolarAstro:{TAU:Math.PI*2,DEG:Math.PI/180,clamp:(v,a,b)=>Math.max(a,Math.min(b,v))},devicePixelRatio:2},context={window,performance};vm.createContext(context);vm.runInContext(read('src/renderer.js'),context);const resize=window.SolarRenderer.prototype.resize;vm.runInContext(read('src/performance.js'),context);assert.equal(window.SolarRenderer.prototype.resize,resize);let calls=0;const r=Object.create(window.SolarRenderer.prototype);Object.assign(r,{canvas:{getBoundingClientRect:()=>({width:100,height:200})},options:{quality:'auto'},ctx:{setTransform(){}},gpu:{resize(){calls++;}},sky:{resize(){}},surface:{invalidate(){}},clearLabels(){},stats:{}});r.resize();assert.equal(r.canvas.width,200);assert.equal(r.canvas.height,400);assert.equal(r.stats.adaptiveDpr,2);r.resize();assert.equal(calls,1);});
test('baked texture preparation skips seam reads; CPU still reads required pixels',()=>{const reads=[],writes=[];class Canvas{constructor(w,h){this.width=w;this.height=h;}getContext(){return {drawImage(){},getImageData(x,y,w,h){reads.push([x,y,w,h]);return {data:new Uint8ClampedArray(w*h*4)};},putImageData(...a){writes.push(a);}};}}const {window}=surfaceContext({OffscreenCanvas:Canvas}),kernel=window.SolarSurface.kernel();assert.equal(kernel.sourceFor({base:'https://cdn.example/',tiers:[{width:256,path:'earth.webp'}],seamBaked:true},256).seamBaked,true);kernel.materialCanvas({},256,128,false,true);assert.equal(reads.length,0);kernel.materialCanvas({},256,128,true,true);assert.deepEqual(reads,[[0,0,256,128]]);assert.equal(writes.length,0);kernel.materialCanvas({},256,128,false,false);assert.equal(reads.length,3);assert.equal(writes.length,2);});
test('worker boot receives the same material style as the compatibility adapter',()=>{let boot='';class B{constructor(parts){this.parts=parts;}}class U extends URL{static createObjectURL(blob){boot=blob.parts.join('');return 'blob:test';}static revokeObjectURL(){}}class Canvas{getContext(){return null;}}class W{terminate(){}postMessage(){}}const {window}=surfaceContext({Blob:B,URL:U,Worker:W,OffscreenCanvas:Canvas}),service=new window.SolarSurface.Service();assert.ok(boot.startsWith('const kernel='));const context={OffscreenCanvas:Canvas,performance,setTimeout,postMessage(){}};vm.createContext(context);vm.runInContext(boot,context);const shader=vm.runInContext('kernel.shaderSources.fragment',context);assert.equal(shader,window.SolarSurface.kernel().shaderSources.fragment);assert.ok(shader.includes(style.warpGLSL));assert.ok(shader.includes(style.lightingGLSL));service.dispose();});
