'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const read=name=>fs.readFileSync(path.join(__dirname,'..',name),'utf8');
function metadata(){const app=read('src/app.js'),a=app.indexOf('  const LANG_ORDER='),b=app.indexOf('  const FACTORY_OPTIONS=',a);assert.ok(a>=0&&b>a);return vm.runInNewContext(app.slice(a,b)+';({order:LANG_ORDER,meta:LANG_META,regions:REGIONS})');}
function detect(zone,languages){const window={};require('./helpers/i18n-runtime.cjs').localization({window,navigator:{languages,language:languages[0]},Intl:{DateTimeFormat:()=>({resolvedOptions:()=>({timeZone:zone})})}});return window.SolarModules.Localization.detect();}
test('Singapore uses one country entry and the existing English payload',()=>{const {order,meta,regions}=metadata();assert.equal(order.filter(c=>c==='sg').length,1);assert.equal(new Set(order).size,order.length);assert.deepEqual(JSON.parse(JSON.stringify(meta.sg)),{code:'SG',name:'Singapore',locale:'en-SG',html:'en-SG',copy:'en'});assert.ok(!fs.existsSync(path.join(__dirname,'../src/locales/sg.json')));for(const code of order){assert.ok(meta[code]&&regions[code],code);assert.ok(fs.existsSync(path.join(__dirname,'../src/locales/'+meta[code].copy+'.json')),code);}});
test('Singapore belongs to the same menu ordering and scroll container',()=>{const html=read('index.html'),{order}=metadata(),a=html.indexOf('id="language-scroll"'),b=html.indexOf('scroll-cue-down',a),block=html.slice(a,b);assert.ok(a>=0&&b>a);const buttons=[...block.matchAll(/data-language="([^"]+)"/g)].map(m=>m[1]);assert.deepEqual(buttons,Array.from(order));assert.match(block,/data-language="sg"><strong>SG<\/strong><span>Singapore<\/span>/);});
test('Singapore detection supports IANA and legacy zone names and en-SG',()=>{assert.equal(detect('Asia/Singapore',['zh-CN']),'sg');assert.equal(detect('Singapore',['en-US']),'sg');assert.equal(detect('Etc/UTC',['en-SG']),'sg');assert.equal(detect('Etc/UTC',['en-SG-u-hc-h23']),'sg');assert.equal(detect('Asia/Seoul',['en-SG']),'kor');assert.equal(detect('Asia/Shanghai',['en-SG']),'chn');assert.equal(detect('Asia/Jakarta',['en-SG']),'id');assert.equal(detect('America/New_York',['en-US']),'en');});
test('Singapore local time handles a date rollover and the existing region coordinates',()=>{const {regions}=metadata(),sg=regions.sg;assert.equal(sg.timeZone,'Asia/Singapore');assert.equal(sg.label,'SINGAPORE');assert.ok(Math.abs(sg.latitude-(1+17/60))<1e-8);assert.equal(sg.longitude,103.85);const format=new Intl.DateTimeFormat('en-SG',{timeZone:sg.timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});const parts=Object.fromEntries(format.formatToParts(new Date('2026-09-18T18:15:00Z')).map(p=>[p.type,p.value]));assert.equal(parts.year,'2026');assert.equal(parts.month,'09');assert.equal(parts.day,'19');assert.equal(parts.hour,'02');assert.equal(parts.minute,'15');});
