'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const code=fs.readFileSync(path.join(__dirname,'../src/ui-runtime.js'),'utf8');
class Element extends EventTarget{
 constructor(tag='div'){super();this.tagName=tag.toUpperCase();this.id=tag;this.hidden=true;this.open=false;this.dataset={};this.classes=new Set();this.removed=false;this.scrollTop=0;this.scrollHeight=300;this.clientHeight=100;this.classList={add:(...v)=>v.forEach(x=>this.classes.add(x)),remove:(...v)=>v.forEach(x=>this.classes.delete(x)),contains:v=>this.classes.has(v),toggle:(v,on)=>on?this.classes.add(v):this.classes.delete(v)};}
 getBoundingClientRect(){return {left:20,top:20,right:220,bottom:220};}
 remove(){this.removed=true;}showModal(){this.open=true;}close(){this.open=false;this.dispatchEvent(new Event('close'));}
 closest(){return this.selectable?this:null;}
}
function harness(reduced=true){
 const timers=new Map(),frames=new Map(),nodes=[],observers=[];let serial=0;
 const doc=new Element();doc.documentElement=new Element('html');doc.createElement=tag=>new Element(tag);doc.head={append:e=>nodes.push(e)};
 const root={document:doc,matchMedia:()=>({matches:reduced}),setTimeout:f=>{const id=++serial;timers.set(id,f);return id;},clearTimeout:id=>timers.delete(id),requestAnimationFrame:f=>{const id=++serial;frames.set(id,f);return id;},cancelAnimationFrame:id=>frames.delete(id),ResizeObserver:class{constructor(f){this.callback=f;observers.push(this);}observe(){}disconnect(){this.disconnected=true;}}};
 vm.runInNewContext(code,{window:root});
 return {root,doc,ui:root.SolarModules.UI,timers,frames,nodes,observers,runTimers(){const a=[...timers.values()];timers.clear();a.forEach(f=>f());}};
}
function pointer(el,type,x,y){const e=new Event(type,{cancelable:true});Object.assign(e,{clientX:x,clientY:y});el.dispatchEvent(e);return e;}
test('top dialog alone closes; a fading card consumes repeated Escape',()=>{const h=harness(false),help=new Element('dialog'),info=new Element('dialog');for(const d of [help,info]){h.ui.bindDialog(d,()=>h.ui.hide(d,()=>d.close()));h.ui.show(d,()=>d.showModal());}assert.equal(h.ui.topDialog(),info);h.ui.dismissTopDialog();assert.ok(info.open&&help.open);h.ui.dismissTopDialog();h.runTimers();assert.equal(info.open,false);assert.ok(help.open);h.ui.dismissTopDialog();h.runTimers();assert.equal(help.open,false);assert.equal(h.ui.dismissTopDialog(),false);});
test('dialog padding stays open; genuine backdrop clicks close',()=>{const h=harness(),d=new Element('dialog');h.ui.bindDialog(d,()=>h.ui.hide(d,()=>d.close()));h.ui.show(d,()=>d.showModal());pointer(d,'pointerdown',25,25);pointer(d,'click',25,25);assert.ok(d.open);pointer(d,'pointerdown',0,0);pointer(d,'click',0,0);assert.equal(d.open,false);});
test('dragging out of a card is not an outside click',()=>{const h=harness(),d=new Element('dialog');h.ui.bindDialog(d,()=>d.close());h.ui.show(d,()=>d.showModal());pointer(d,'pointerdown',100,100);pointer(d,'click',0,0);assert.ok(d.open);});
test('native cancel follows the registered lifecycle',()=>{const h=harness(),a=new Element('dialog'),b=new Element('dialog');for(const d of [a,b]){h.ui.bindDialog(d,()=>h.ui.hide(d,()=>d.close()));h.ui.show(d,()=>d.showModal());}const e=new Event('cancel',{cancelable:true});b.dispatchEvent(e);assert.ok(e.defaultPrevented);assert.ok(a.open);assert.equal(b.open,false);});
test('failed lazy load removes its node and retries with a new request',async()=>{const h=harness(),first=h.ui.loadScript('notes.js?v=1','Notes'),rejected=assert.rejects(first,/Could not load/);assert.equal(h.ui.loadScript('notes.js?v=1','Notes'),first);h.nodes[0].dispatchEvent(new Event('error'));await rejected;assert.ok(h.nodes[0].removed);const second=h.ui.loadScript('notes.js?v=1','Notes');assert.equal(h.nodes.length,2);h.root.Notes={ready:true};h.nodes[1].dispatchEvent(new Event('load'));assert.equal(await second,h.root.Notes);assert.equal(h.timers.size,0);});
test('missing script exports reject instead of waiting indefinitely',async()=>{const h=harness(),task=h.ui.loadScript('notes','Notes'),rejected=assert.rejects(task,/did not initialize/);h.nodes[0].dispatchEvent(new Event('load'));await rejected;assert.ok(h.nodes[0].removed);});
test('hung scripts time out; final disposal cancels pending work',async()=>{const h=harness(),task=h.ui.loadScript('notes','Notes'),rejected=assert.rejects(task,/Timed out/);h.runTimers();await rejected;const again=h.ui.loadScript('notes','Notes'),cancelled=assert.rejects(again,/disposed/);h.ui.dispose();await cancelled;assert.equal(h.timers.size,0);});
test('scroll observers and pending animation frames have one teardown owner',()=>{const h=harness(false),card=new Element(),body=new Element();const binding=h.ui.bindScrollCues(card,body);binding.update();assert.ok(card.classes.has('can-scroll-down'));body.scrollTop=200;body.dispatchEvent(new Event('scroll'));assert.ok(card.classes.has('can-scroll-up'));assert.ok(!card.classes.has('can-scroll-down'));h.observers[0].callback();h.ui.show(card);h.ui.dispose();assert.ok(h.observers[0].disconnected);assert.equal(h.frames.size,0);});
test('diagnostics and inputs are selectable while scene selection stays blocked',()=>{const h=harness();h.ui.installDocumentGuards(h.doc);let e=new Event('selectstart',{cancelable:true});h.doc.dispatchEvent(e);assert.ok(e.defaultPrevented);h.doc.selectable=true;e=new Event('selectstart',{cancelable:true});h.doc.dispatchEvent(e);assert.equal(e.defaultPrevented,false);h.ui.dispose();h.doc.selectable=false;e=new Event('selectstart',{cancelable:true});h.doc.dispatchEvent(e);assert.equal(e.defaultPrevented,false);});
