/* Generate offline assets and the drop-in sky override from one image source. */
'use strict';
const fs=require('node:fs'),path=require('node:path'),root=path.resolve(__dirname,'..');
const assetRevision=JSON.parse(fs.readFileSync(path.join(root,'assets/revision.json'),'utf8')).version;
if(!/^assetpack-[a-z0-9-]+$/i.test(assetRevision))throw Error('Invalid assets/revision.json version.');
const materials={};
const skyFile='universe-optimized.webp';
const required=['sun','mercury','venus','earth','mars','jupiter','saturn','uranus','neptune','pluto','moon','europa','clouds'];
for(const id of required)if(!fs.existsSync(path.join(root,'assets',id+'.webp')))throw Error('Missing original asset: assets/'+id+'.webp');
for(const name of fs.readdirSync(path.join(root,'assets')).filter(n=>n.endsWith('.webp')&&!['universe.webp',skyFile,'pluto-relief.webp'].includes(n)))materials[name.slice(0,-5)]='data:image/webp;base64,'+fs.readFileSync(path.join(root,'assets',name)).toString('base64');
const sky='data:image/webp;base64,'+fs.readFileSync(path.join(root,'assets',skyFile)).toString('base64');
const stars=JSON.parse(fs.readFileSync(path.join(root,'assets/stars.json'),'utf8'));
if(!Array.isArray(stars))throw Error('assets/stars.json must be an array');
const materialInfo=JSON.parse(fs.readFileSync(path.join(root,'assets/material-info.json'),'utf8'));
const data={materials,materialInfo,sky,stars,skyVersion:assetRevision};
function atomicWrite(file,text){const tmp=file+'.tmp';try{fs.writeFileSync(tmp,text,'utf8');fs.renameSync(tmp,file);}finally{if(fs.existsSync(tmp))fs.unlinkSync(tmp);}}
atomicWrite(path.join(root,'src/assets.js'),'/* Generated by tools/pack_assets.cjs; offline assets, no remote requests. */\nwindow.SolarAssets='+JSON.stringify(data)+';\n');
atomicWrite(path.join(root,'src/sky-asset.js'),'/* Generated sky-only payload: load after src/assets.js. */\n(function(root){\'use strict\';\nif(!root.SolarAssets)throw Error(\'SolarAssets must load before sky-asset.js\');\nroot.SolarAssets.sky='+JSON.stringify(sky)+';\nroot.SolarAssets.skyVersion='+JSON.stringify(assetRevision)+';\n})(window);\n');
