'use strict';
const fs=require('node:fs'),path=require('node:path'),root=path.resolve(__dirname,'..'),materials={};
for(const name of fs.readdirSync(path.join(root,'assets')).filter(n=>n.endsWith('.webp')&&n!=='universe.webp'))materials[name.replace('.webp','')]='data:image/webp;base64,'+fs.readFileSync(path.join(root,'assets',name)).toString('base64');
const data={materials,sky:'data:image/webp;base64,'+fs.readFileSync(path.join(root,'assets/universe.webp')).toString('base64'),stars:JSON.parse(fs.readFileSync(path.join(root,'assets/stars.json'),'utf8'))};
fs.writeFileSync(path.join(root,'src/assets.js'),'/* Generated by tools/pack_assets.cjs; offline assets, no remote requests. */\nwindow.SolarAssets='+JSON.stringify(data)+';\n');
